const wardrobe = {
  lowers: [
    {id:'LW-001', brand:"Levi's", color:'Jet Black', type:'Slim Fit Chinos', hex:'#0b0b0d', category:'chinos', formality:6, smart:9, casual:7, party:8},
    {id:'LW-002', brand:"Levi's", color:'Light Blue', type:'Washed Slim Fit Jeans', hex:'#8fb5d7', category:'jeans', formality:3, smart:8, casual:9, party:8},
    {id:'LW-003', brand:"Levi's", color:'Dark Indigo', type:'Slim Fit Jeans', hex:'#17263f', category:'jeans', formality:4, smart:10, casual:10, party:10},
    {id:'LW-004', brand:"Levi's", color:'Charcoal Grey', type:'Formal Trousers', hex:'#3f4145', category:'formal', formality:8, smart:7, casual:5, party:7},
    {id:'LW-005', brand:"Levi's", color:'Ice Blue', type:'Washed Slim Fit Jeans', hex:'#bfd8ea', category:'jeans', formality:2, smart:7, casual:9, party:8},
    {id:'LW-006', brand:'Peter England', color:'Jet Black', type:'Formal Trousers', hex:'#050505', category:'formal', formality:9, smart:7, casual:4, party:7},
    {id:'LW-007', brand:'Decathlon', color:'Jet Black', type:'Joggers', hex:'#09090b', category:'joggers', formality:1, smart:2, casual:8, party:4},
    {id:'LW-008', brand:'Decathlon', color:'Navy Blue', type:'Joggers', hex:'#17253f', category:'joggers', formality:1, smart:2, casual:8, party:4},
    {id:'LW-009', brand:'HRX', color:'Jet Black', type:'Joggers', hex:'#08080a', category:'joggers', formality:1, smart:2, casual:8, party:4},
    {id:'LW-010', brand:'HRX', color:'Steel Blue', type:'Joggers', hex:'#49606d', category:'joggers', formality:1, smart:2, casual:8, party:4},
    {id:'LW-011', brand:'HRX', color:'Midnight Blue', type:'Joggers', hex:'#0d1d35', category:'joggers', formality:1, smart:2, casual:8, party:4},
    {id:'LW-012', brand:'Brava Tex', color:'Jet Black', type:'Shorts', hex:'#08080a', category:'shorts', formality:0, smart:0, casual:7, party:2},
    {id:'LW-013', brand:'Brava Tex', color:'Charcoal Grey', type:'Shorts', hex:'#3d3d3f', category:'shorts', formality:0, smart:0, casual:7, party:2},
    {id:'LW-014', brand:'Brava Tex', color:'Navy Blue', type:'Shorts', hex:'#15243d', category:'shorts', formality:0, smart:0, casual:7, party:2},
    {id:'LW-015', brand:'Brava Tex', color:'Olive Green', type:'Shorts', hex:'#4f5a3c', category:'shorts', formality:0, smart:0, casual:7, party:2},
    {id:'LW-016', brand:'Louis Philippe', color:'Olive Sage Green Micro Check', type:'Formal Trousers', hex:'#9aa78f', category:'formal', formality:9, smart:8, casual:6, party:8},
    {id:'LW-017', brand:'Louis Philippe', color:'Royal Blue Windowpane Check', type:'Formal Trousers', hex:'#315d92', category:'formal', formality:9, smart:8, casual:6, party:8},
    {id:'LW-018', brand:'Louis Philippe', color:'Charcoal Grey Micro Check', type:'Formal Trousers', hex:'#646466', category:'formal', formality:9, smart:8, casual:6, party:8}
  ],
  uppers: [
    {id:'UP-001', brand:'Knighthood', color:'Light Grey Micro Check', type:'Slim Fit Formal Shirt', hex:'#b7b7b0', category:'formal', pattern:true, solid:false, formality:8, smart:8, casual:5, party:7},
    {id:'UP-002', brand:'Highlander', color:'Jet Black', type:'Solid Formal Shirt', hex:'#070707', category:'formal', pattern:false, solid:true, formality:8, smart:9, casual:7, party:10},
    {id:'UP-003', brand:'Knighthood', color:'Royal Blue Micro Dot', type:'Slim Fit Formal Shirt', hex:'#173f9b', category:'formal', pattern:true, solid:false, formality:8, smart:8, casual:6, party:8},
    {id:'UP-004', brand:'Knighthood', color:'Royal Blue Micro Check', type:'Slim Fit Formal Shirt', hex:'#173b82', category:'formal', pattern:true, solid:false, formality:8, smart:8, casual:6, party:8},
    {id:'UP-005', brand:'Nautica', color:'Jet Black Textured', type:'Slim Fit Formal Shirt', hex:'#080808', category:'formal', pattern:false, solid:true, formality:8, smart:9, casual:7, party:10},
    {id:'UP-006', brand:'Highlander', color:'Olive Green Textured', type:'Formal Shirt', hex:'#5a6643', category:'formal', pattern:false, solid:true, formality:8, smart:9, casual:8, party:9},
    {id:'UP-007', brand:'Ultrapress', color:'Steel Grey', type:'Solid Formal Shirt', hex:'#76787c', category:'formal', pattern:false, solid:true, formality:9, smart:8, casual:5, party:7},
    {id:'UP-008', brand:'Austin Reed', color:'Dusty Purple Textured', type:'Formal Shirt', hex:'#7561a7', category:'formal', pattern:false, solid:true, formality:8, smart:8, casual:6, party:8},
    {id:'UP-009', brand:'Gold Line', color:'Sky Blue Geometric Print', type:'Formal Shirt', hex:'#bfd5e1', category:'formal', pattern:true, solid:false, formality:7, smart:8, casual:6, party:7},
    {id:'UP-010', brand:'Peter England', color:'Mint Blue', type:'Solid Formal Shirt', hex:'#a6e2e7', category:'formal', pattern:false, solid:true, formality:9, smart:10, casual:7, party:8},
    {id:'UP-011', brand:'Highlander', color:'Jet Black', type:'Full Sleeve Formal Shirt', hex:'#050505', category:'formal', pattern:false, solid:true, formality:9, smart:9, casual:7, party:10},
    {id:'UP-012', brand:'Symbol', color:'White', type:'Formal Shirt ×7', hex:'#f8f6f0', category:'formal', pattern:false, solid:true, white:true, formality:10, smart:9, casual:5, party:8},
    {id:'UP-013', brand:'Highlander', color:'White', type:'Formal Shirt', hex:'#ffffff', category:'formal', pattern:false, solid:true, white:true, formality:10, smart:9, casual:5, party:8},
    {id:'UP-014', brand:'Knighthood', color:'White', type:'Formal Shirt', hex:'#f7f7f2', category:'formal', pattern:false, solid:true, white:true, formality:10, smart:9, casual:5, party:8},
    {id:'UP-015', brand:'Max', color:'Blue & Mint Green Plaid', type:'Casual Shirt', hex:'#3a7c86', category:'casualShirt', pattern:true, solid:false, formality:4, smart:8, casual:9, party:8},
    {id:'UP-016', brand:'Buffalo', color:'Indigo Denim', type:'Casual Shirt', hex:'#254b73', category:'casualShirt', pattern:false, solid:true, formality:4, smart:8, casual:9, party:9},
    {id:'UP-017', brand:'DJ&C', color:'Olive Green', type:'Mandarin Collar Casual Shirt', hex:'#7b815f', category:'casualShirt', pattern:false, solid:true, formality:5, smart:9, casual:9, party:9},
    {id:'UP-018', brand:'Live Smart', color:'Light Pink Linen', type:'Casual Shirt', hex:'#efc7cf', category:'casualShirt', pattern:false, solid:true, formality:4, smart:8, casual:8, party:8},
    {id:'UP-019', brand:'Emerized Plaids', color:'Red, White & Navy Vertical Striped', type:'Casual Shirt', hex:'#8f2636', category:'casualShirt', pattern:true, solid:false, formality:4, smart:7, casual:8, party:8},
    {id:'UP-020', brand:'Shirt Theory', color:'Mustard Printed', type:'Casual Shirt', hex:'#d39a2b', category:'casualShirt', pattern:true, solid:false, formality:3, smart:7, casual:9, party:9},
    {id:'UP-021', brand:'Buffalo Knit Wear', color:'Black & Red Vertical Striped', type:'Casual Shirt', hex:'#7b1f2a', category:'casualShirt', pattern:true, solid:false, formality:4, smart:8, casual:8, party:9},
    {id:'UP-022', brand:'Buffalo Knit Wear', color:'Black & Blue Horizontal Striped', type:'Casual Shirt', hex:'#25487e', category:'casualShirt', pattern:true, solid:false, formality:3, smart:7, casual:8, party:8},
    {id:'UP-023', brand:'Stellers', color:'Olive Green', type:'Narayana Health Polo T-Shirt', hex:'#687149', category:'polo', pattern:false, solid:true, formality:4, smart:7, casual:8, party:5},
    {id:'UP-024', brand:'Originals', color:'Heather Blue', type:'Full Sleeve T-Shirt', hex:'#626d96', category:'tee', pattern:false, solid:true, formality:2, smart:6, casual:8, party:6},
    {id:'UP-025', brand:'Bewakoof', color:'Navy Blue', type:'"How’s The Josh?" Graphic T-Shirt', hex:'#13213c', category:'graphicTee', pattern:true, solid:false, formality:1, smart:3, casual:8, party:6},
    {id:'UP-026', brand:'DAMENSCH', color:'Dark Grey', type:'Pullover Hoodie', hex:'#5c5d63', category:'hoodie', pattern:false, solid:true, formality:1, smart:3, casual:9, party:6},
    {id:'UP-027', brand:'Live Smart', color:'White', type:'Crew Neck T-Shirt', hex:'#f7f7f0', category:'tee', pattern:false, solid:true, formality:2, smart:7, casual:9, party:9},
    {id:'UP-028', brand:'Transspirit', color:'Black & Grey', type:'Raglan Henley T-Shirt', hex:'#222222', category:'tee', pattern:false, solid:true, formality:2, smart:6, casual:8, party:7},
    {id:'UP-029', brand:'Marvel', color:'Black', type:'Spider-Man Graphic T-Shirt', hex:'#080808', category:'graphicTee', pattern:true, solid:false, formality:1, smart:3, casual:8, party:7},
    {id:'UP-030', brand:"Levi's", color:'White', type:'Crew Neck T-Shirt', hex:'#ffffff', category:'tee', pattern:false, solid:true, formality:2, smart:8, casual:10, party:10},
    {id:'UP-031', brand:'Qute', color:'Brown', type:'Performance V-Neck T-Shirt', hex:'#806b58', category:'tee', pattern:true, solid:false, formality:2, smart:5, casual:7, party:5},
    {id:'UP-032', brand:"Levi's", color:'Jet Black', type:'Crew Neck T-Shirt', hex:'#050505', category:'tee', pattern:false, solid:true, formality:2, smart:8, casual:9, party:10},
    {id:'UP-033', brand:"Levi's", color:'White', type:'Crew Neck T-Shirt', hex:'#f6f6f0', category:'tee', pattern:false, solid:true, formality:2, smart:8, casual:10, party:10},
    {id:'UP-034', brand:'Bewakoof', color:'Black', type:'Graphic T-Shirt', hex:'#080808', category:'graphicTee', pattern:true, solid:false, formality:1, smart:4, casual:8, party:7},
    {id:'UP-035', brand:'DJ&C', color:'Blue Denim', type:'Denim Jacket', hex:'#1d4068', category:'outerwear', pattern:false, solid:true, formality:3, smart:7, casual:9, party:10},
    {id:'UP-036', brand:'Highlander', color:'Jet Black', type:'Casual Overshirt / Shacket', hex:'#080808', category:'outerwear', pattern:false, solid:true, formality:5, smart:8, casual:8, party:9},
    {id:'UP-037', brand:'Manyavar', color:'Sky Blue', type:'Solid Kurta', hex:'#a6cfe8', category:'kurta', pattern:false, solid:true, formality:4, smart:6, casual:8, party:6},
    {id:'UP-038', brand:'Manyavar', color:'Lime Green Striped', type:'Kurta', hex:'#c3cb45', category:'kurta', pattern:true, solid:false, formality:4, smart:5, casual:8, party:6},
    {id:'UP-039', brand:'Manyavar', color:'Royal Blue', type:'Solid Kurta', hex:'#143ca0', category:'kurta', pattern:false, solid:true, formality:4, smart:6, casual:8, party:7},
    {id:'UP-040', brand:'Manyavar', color:'Aqua Blue', type:'Solid Kurta', hex:'#4dc8cf', category:'kurta', pattern:false, solid:true, formality:4, smart:6, casual:8, party:7},
    {id:'UP-041', brand:'Manyavar', color:'Mustard Yellow Embroidered', type:'Kurta', hex:'#d19439', category:'kurta', pattern:true, solid:false, formality:5, smart:5, casual:8, party:7},
    {id:'UP-042', brand:'Manyavar', color:'Baby Pink Textured', type:'Kurta', hex:'#ef9ebd', category:'kurta', pattern:true, solid:false, formality:4, smart:5, casual:8, party:7},
    {id:'UP-043', brand:'Manyavar', color:'Navy Blue Embroidered', type:'Kurta', hex:'#08375e', category:'kurta', pattern:true, solid:false, formality:5, smart:6, casual:9, party:8}
  ],
  footwear: [
    {id:'FW-001', brand:'Khadims', color:'Medium Brown', type:'Leather Sandals', hex:'#7a4a2a', openToe:true, category:'sandals', formal:1, smart:2, casual:6, party:2},
    {id:'FW-002', brand:'Khadims', color:'Olive Green', type:'Casual Slides', hex:'#596a52', openToe:true, category:'slides', formal:0, smart:1, casual:5, party:1},
    {id:'FW-003', brand:'Nike', color:'White', type:'Premium Lifestyle Sneakers', hex:'#f7f7f2', openToe:false, category:'sneakers', formal:4, smart:10, casual:10, party:10},
    {id:'FW-004', brand:'Adidas', color:'Navy Blue', type:'Running Sneakers', hex:'#172850', openToe:false, category:'sneakers', formal:2, smart:6, casual:8, party:5},
    {id:'FW-005', brand:'Bata', color:'Jet Black', type:'Formal Shoes', hex:'#040404', openToe:false, category:'formalShoes', formal:10, smart:7, casual:3, party:7}
  ],
  suits: [
    {id:'SU-001', brand:'British Cut Suit', color:'Navy Blue Double-Breasted', type:'Suit', hex:'#171c38', priority:10},
    {id:'SU-002', brand:'American Cut Suit', color:'Navy Blue Single-Breasted', type:'Suit', hex:'#202942', priority:7}
  ],
  ties: [
    {id:'TI-001', brand:'Tie', color:'Maroon & Silver Diagonal Stripe', type:'Silk Tie', hex:'#7a1f35'},
    {id:'TI-002', brand:'Tie', color:'Navy Blue, Maroon & Silver Diagonal Stripe', type:'Silk Tie', hex:'#142c66'},
    {id:'TI-003', brand:'Tie', color:'Chocolate Brown & Silver Diagonal Stripe', type:'Silk Tie', hex:'#5a3a24'}
  ]
};
